import type { Metadata } from "next"
import "./globals.css";
import {Inter} from "next/font/google"
import Header from "@/components/layout/Header";

const inter = Inter({subsets: ["latin"]});


export const metadata: Metadata = {
  title: "myApp",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className = {`${inter.className} antialiased bg-white min-h-[120vh]`}>
        <Header />
        {children}
        </body>
    </html>
  )
}
